import './globals.css'
import type {Metadata} from 'next'
import {MainLayoutClient} from '@/components/main-layout.client'
import {roboto} from '@/lib/fonts'


export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
                                      children,
                                   }: {
   children: React.ReactNode
}) {
   return (
      <html data-theme={'legendisTheme'} lang='en'>
      <body className={`${roboto.className} bg-base-100 text-base-content`}>
      <MainLayoutClient>{children}</MainLayoutClient></body>
      </html>
   )
}
