import {MainLayoutClient} from '@/components/main-layout.client';
import {italianno, roboto, tangerine} from '@/lib/fonts';
import type {Metadata} from 'next';
import './globals.css';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
   return (
      <html
         data-theme={'legendisTheme'}
         lang='en'>
         <body
            className={`relative ${roboto.className} ${italianno.className} ${tangerine.className}`}>
            <MainLayoutClient>{children}</MainLayoutClient>
         </body>
      </html>
   );
}
